#!/bin/sh

# the next line is for chkconfig
# chkconfig: 345 90 10
# description: please, please work


if [ $(whoami) != "root" ]; then
  echo "You must be root."
  exit 1
fi

case $1 in
  stop)

    su gites -c \
      "/home/gites/gites-alloch-website/bin/instance $*" \
      </dev/null

    ;;
  restart)

    ${0} stop
    sleep 1
    ${0} start

    ;;
  *)

    su gites -c \
      "/home/gites/gites-alloch-website/bin/instance $*" \
       </dev/null

    ;;
esac

